### PR TITLE
Add support for Rails 7

### PR DESCRIPTION
**Pull request by common-nighthawk**
With Rails 7.0 just out, this change makes pg_serializable compatible
with the new release. Reading through the docs, I don't expect any
changes to ActiveRecord and ActiveSupport to be incompatible.

This also: runs `bundle update` to get all dependencies up to date
(codecov 0.1.14 has been yanked/is no longer available) and bumps this
gems minor version for a new release.

If it's helpful to break these out into separate PRs, just let me know!

### CODE REVIEW

**Comment by matthewjf** [comment]
Thanks for opening this PR @common-nighthawk! 

The tests in this project don't run automatically, they need to be run locally. Did you happen to verify that all the tests are passing? I don't have a ruby environment setup right now.

**Comment by common-nighthawk** [comment]
@matthewjf Thanks for being so responsive!  Good call—the tests did not pass locally.  Luckily I didn't need to update any application logic to get them working—just some tweaks loading the test files to work with the new autoloader.  PR updated.

Screen Shot 2021-12-21 at 3 48 10 PM

**Comment by common-nighthawk** [comment]
@matthewjf Out of scope for this PR, but not sure of a better place to chat—

I'll need to do the same thing with:
https://github.com/hoverinc/active_record-log_deleted
https://github.com/hoverinc/state_machines-after_transition_commit

These repos are owned by `hoverinc`, so will be easy to make changes.  But it looks like you are the only owner on RubyGems.org:
https://rubygems.org/gems/active_record-log_deleted/versions/0.2.2
https://rubygems.org/gems/state_machines-after_transition_commit/versions/0.1.2

Would you be comfortable [adding me](https://rubygems.org/profiles/common-nighthawk) to those projects so I can cut new releases after making the updates?

**Comment by matthewjf** [comment]
@common-nighthawk Sure thing, I will add you as an owner to those other gems. For this particular PR, do you happen to know if the autoload changes are backwards compatible?

**Comment by common-nighthawk** [comment]
@matthewjf Thanks!  Yes—everything is backwards compatible.  Screenshot attached of specs passing with current code on master + only the autoload changes.

**Pull request merged**
